version: "3.7"
services:
  parse:
    build: ./parse
    depends_on:
      - parse-db
    secrets:
      - parse_server_application_id
      - parse_server_master_key
    ports:
      - "1337:1337"

  parse-db:
    image: mongo
    expose:
      - "27017"

  mqtt:
    build: ./mqtt
    ports:
      - "1883:1883"

secrets:
  parse_server_application_id:
    file: ./secrets/PARSE_SERVER_APPLICATION_ID
  parse_server_master_key:
    file: ./secrets/PARSE_SERVER_MASTER_KEY
