version: "3.7"
services:
  parse:
    build: ./parse
    depends_on:
      - parse-db
    secrets:
      - parse_server_application_id
      - parse_server_master_key
    ports:
      - "1337:1337"

  parse-db:
    image: mongo
    expose:
      - "27017"

  mqtt:
    build: ./mqtt
    ports:
      - "1883:1883"

  microservices:
    build: ./microservices
    volumes:
      - ./microservices:/usr/share/microservices
    secrets:
      - parse_server_application_id
      - parse_server_master_key

  microservices-db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/microservices_database_password
      - MYSQL_DATABASE_FILE=/run/secrets/microservices_database_name
    expose:
      - "3306"
    secrets:
      - microservices_database_password
      - microservices_database_name
    volumes:
      - ./mariadb_data:/var/lib/mysql

secrets:
  parse_server_application_id:
    file: ./secrets/PARSE_SERVER_APPLICATION_ID
  parse_server_master_key:
    file: ./secrets/PARSE_SERVER_MASTER_KEY
  microservices_database_password:
    file: ./secrets/MICROSERVICES_DATABASE_PASSWORD
  microservices_database_name:
    file: ./secrets/MICROSERVICES_DATABASE_NAME
